### ISSUE TITLE
stream comparison fails for 2 identical files having same content

### ISSUE THREAD

**Issue by bhaskerchari** [kevinoid/stream-compare#21]
I am trying to use node-stream-equal to compare two zip files which actually may have a single excel/ppt/csv files and is zipped for compressing the size but the stream comparison always returns false.

```
var fs = require('fs');
var path = require('path');

function compareStreams(file1Path, file2Path) {
	const streamEqual = require('stream-equal');
	const fs = require('fs');
	var file1 = path.resolve(__dirname, file1Path);
	var file2 = path.resolve(__dirname, file2Path);

	let readStream1 = fs.createReadStream(file1);
	let readStream2 = fs.createReadStream(file2);
	streamEqual(readStream1, readStream2, (err, equal) => {
		console.log(equal); // true
	});
}
```

```
// This always logs false
compareStreams(''./excel1.zip'', './excel2.zip');
```

I have even tried unzipping it and directly comared the excel files still it logs false and I am sure the contents of excel files are exactly identical.
`compareStreams(''./excel1.xlsx'', './excel2.xlsx');`

But one thing I have noticed is if I create a copy of 1 file and compare with its copy then it is logging true.

`For ex: compareStreams(''./excel1.xlsx'', './excel1 - Copy.xlsx'); // logs true to console.`

I am wondering if it has something to do with the timestamp and especially the modified date of the file.

Any body has any suggestions on this?

**Comment by kevinoid** [comment]
Your example uses [`stream-equal`](https://github.com/fent/node-stream-equal).  You may want to report the issue to that project.  If you are also experiencing a similar problem with `stream-compare`, feel free to reopen this issue with an example using this module.

**Comment by kevinoid** [comment]
Also note that `stream-compare` (this module) compares the events emitted by each stream, so even if the file data is the same, the events may not be (e.g. if the read sizes are different due to caching or filesystem differences).

**Comment by bhaskerchari** [comment]
@kevinoid,

Yes actually I was trying with both stream-compare and stream-equal as well both didn't work for me and sorry I posted the code for stream-equal but it's just the package name change.

However based on my requirement I want to compare 2 identical excel/ppt/csv files which may have exact same content. But I couldn't figure out how it can be done in an easier way either by stream comparison or even buffer comparison also didn't help.

I've done more research but not much success.

I'm just wondering how it would be possible to ignore certain things such as time stamp and any other metadata while doing comparison and only consider contents to match up.

But I didn't find any node package on the web which does what I am looking for...

Do you have any thoughts oe suggestions for the same?

Ideally I was expecting stream-equal or stream-compare to work for such cases where it should be accepting some metaconfig where it ignores certain things like timestamp and other meta file info and focuses on comparing the contents and it does sound a natural case to me.

**Comment by kevinoid** [comment]
It sounds like an appropriate solution would depend on what you consider to be "content" and "metadata":

* If "metadata" is filesystem metadata and "content" is file content, then reading the content of each file into a `Buffer` and comparing would be a simple solution.  (I assume this is not the case since you said "even buffer comparison also didn't help".)
* If you are dealing with standardized compression formats (`.xlsx`/`.pptx` and `.csv.gz`) and want to ignore the compression metadata, then extracting the contents using [`yauzl`](https://github.com/thejoshwolfe/yauzl) (for ZIP) or [`zlib`](https://nodejs.org/api/zlib.html) (for Gzip) and comparing the unzipped contents would suffice.
* More likely you want to ignore format-specific metadata, which would require code or a library which understands the internals of the file formats and can selectively ignore things you would consider metadata (e.g. the `docProps` directory in `.xlsx`/`.pptx`).  It could be further complicated if you consider formatting to be metadata rather than content.  In any case, your specific requirements will strongly influence the solution.

Best of luck,
Kevin
